// gen-headers generates c/opcodes.h and c/adapter_types.h from the Go constants.
// Run via: go generate ./...
// CI verify: go generate ./... && git diff --exit-code c/
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/superbrobenji/planetopia-protocol/adapter"
	"github.com/superbrobenji/planetopia-protocol/opcodes"
)

func main() {
	root := repoRoot()
	must(writeOpcodesHeader(filepath.Join(root, "c", "opcodes.h")))
	must(writeAdapterTypesHeader(filepath.Join(root, "c", "adapter_types.h")))
}

func writeOpcodesHeader(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprint(f, `// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: opcodes/opcodes.go — run "go generate ./..." to regenerate.

#pragma once

/* Planetopia mesh protocol opcode constants.
 * Byte 0 of the data payload in MessageTypeSerialCmdBroadcast frames. */

/* Server → node: management */
`)
	writeCDefByte(f, "OP_NODE_ID_SET", opcodes.OpNodeIdSet, "assign logical node ID")
	writeCDefByte(f, "OP_CONFIG_SET", opcodes.OpConfigSet, "set adapter type and config")
	writeCDefByte(f, "OP_TX_POWER_SET", opcodes.OpTxPowerSet, "set TX power preset")
	fmt.Fprint(f, "\n/* Server → output node: LED/relay commands */\n")
	writeCDefByte(f, "OP_LED_SOLID", opcodes.OpLEDSolid, "solid colour: [r,g,b] at bytes [1:4]")
	writeCDefByte(f, "OP_LED_OFF", opcodes.OpLEDOff, "turn LED strip off")
	writeCDefByte(f, "OP_LED_BLINK", opcodes.OpLEDBlink, "blink: [r,g,b,interval_hi,interval_lo] at [1:6]")
	writeCDefByte(f, "OP_RELAY_SET", opcodes.OpRelaySet, "relay state: [0x00=off, 0x01=on] at byte [1]")
	fmt.Fprint(f, "\n/* Node → server: acknowledgement */\n")
	writeCDefByte(f, "OP_COMMAND_ACK", opcodes.OpCommandAck, "acknowledge a received command")
	return nil
}

func writeAdapterTypesHeader(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprint(f, `// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: adapter/types.go — run "go generate ./..." to regenerate.

#pragma once

/* Planetopia adapter type identifiers.
 * Carried in health report frames and config set commands. */

`)
	writeCDefInt32(f, "ADAPTER_TYPE_UNKNOWN", adapter.TypeUnknown, "not yet configured")
	writeCDefInt32(f, "ADAPTER_TYPE_SERIAL", adapter.TypeSerial, "serial management (internal)")
	writeCDefInt32(f, "ADAPTER_TYPE_PIR", adapter.TypePIR, "passive infrared motion sensor (INPUT)")
	writeCDefInt32(f, "ADAPTER_TYPE_LED", adapter.TypeLED, "LED strip (OUTPUT)")
	writeCDefInt32(f, "ADAPTER_TYPE_RELAY", adapter.TypeRelay, "relay switch (OUTPUT)")
	return nil
}

func writeCDefByte(f *os.File, name string, val byte, comment string) {
	fmt.Fprintf(f, "#define %-20s 0x%02X  /* %s */\n", name, val, comment)
}

func writeCDefInt32(f *os.File, name string, val int32, comment string) {
	fmt.Fprintf(f, "#define %-24s %d  /* %s */\n", name, val, comment)
}

func repoRoot() string {
	// The generator lives at cmd/gen-headers/main.go; repo root is two levels up.
	exe, err := os.Executable()
	must(err)
	// During `go run`, the executable is in a temp dir — use the working directory instead.
	wd, err := os.Getwd()
	must(err)
	_ = exe
	// Walk up until we find go.mod
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "gen-headers: could not find repo root (no go.mod found)")
			os.Exit(1)
		}
		dir = parent
	}
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-headers:", err)
		os.Exit(1)
	}
}
