// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: adapter/types.go — run "go generate ./..." to regenerate.

#pragma once

/* Planetopia adapter type identifiers.
 * Carried in health report frames and config set commands. */

#define ADAPTER_TYPE_UNKNOWN     0  /* not yet configured */
#define ADAPTER_TYPE_SERIAL      1  /* serial management (internal) */
#define ADAPTER_TYPE_PIR         2  /* passive infrared motion sensor (INPUT) */
#define ADAPTER_TYPE_LED         3  /* LED strip (OUTPUT) */
#define ADAPTER_TYPE_RELAY       4  /* relay switch (OUTPUT) */
