// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: opcodes/opcodes.go — run "go generate ./..." to regenerate.

#pragma once

/* Planetopia mesh protocol opcode constants.
 * Byte 0 of the data payload in MessageTypeSerialCmdBroadcast frames. */

/* Server → node: management */
#define OP_NODE_ID_SET       0xC0  /* assign logical node ID */
#define OP_CONFIG_SET        0xC1  /* set adapter type and config */
#define OP_TX_POWER_SET      0xC2  /* set TX power preset */

/* Server → output node: LED/relay commands */
#define OP_LED_SOLID         0xD0  /* solid colour: [r,g,b] at bytes [1:4] */
#define OP_LED_OFF           0xD1  /* turn LED strip off */
#define OP_LED_BLINK         0xD2  /* blink: [r,g,b,interval_hi,interval_lo] at [1:6] */
#define OP_RELAY_SET         0xD8  /* relay state: [0x00=off, 0x01=on] at byte [1] */

/* Node → server: acknowledgement */
#define OP_COMMAND_ACK       0xE0  /* acknowledge a received command */
